#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOO_REPO_ROOT="$ROOT_DIR"
source "$ROOT_DIR/scripts/lib/vt-dylib-env.sh"

usage() {
  cat <<'EOF'
Usage: bash scripts/test-runtime-view-e2e-metrics.sh [options]

Runs the deterministic runtime-view e2e metrics baseline. The desktop lane
creates 2 tabs, splits tab 2 into 3 panes, streams generated unicode/emoji
terminal output, exercises focus/tab/statusbar/resize interactions, and writes
metrics artifacts. The iOS lane reuses the real-device signpost verifier with
runtime-view-e2e inputs when --ios-device-id is supplied.

Options:
  --seed N                 deterministic workload seed (default: 42)
  --bytes-per-pane N       generated bytes per stream/pane (default: 1048576)
  --output-dir PATH        artifacts directory (default: bench/generated/runtime-view-e2e/run-<timestamp>)
  --desktop-only           skip the iOS lane even if device flags are present
  --ios-device-id UDID     run real-device signpost verification lane
  --team-id TEAM_ID        development team for iOS device build/signing
  --vt-lib-dir PATH
  --terminal-body-impl NAME
  -h, --help
EOF
}

require_arg() {
  if [[ $# -lt 2 ]]; then
    echo "Missing value for $1" >&2
    usage >&2
    exit 2
  fi
}

SEED=42
BYTES_PER_PANE=1048576
OUTPUT_DIR=""
DESKTOP_ONLY=0
IOS_DEVICE_ID="${BOO_IOS_DEVICE_ID:-}"
TEAM_ID="${BOO_IOS_TEAM_ID:-}"
VT_LIB_DIR="${BOO_VT_LIB_DIR:-${VT_LIB_DIR:-}}"
TERMINAL_BODY_IMPL="${BOO_TERMINAL_BODY_IMPL:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed)
      require_arg "$@"; SEED="$2"; shift 2 ;;
    --bytes-per-pane)
      require_arg "$@"; BYTES_PER_PANE="$2"; shift 2 ;;
    --output-dir)
      require_arg "$@"; OUTPUT_DIR="$2"; shift 2 ;;
    --desktop-only)
      DESKTOP_ONLY=1; shift ;;
    --ios-device-id)
      require_arg "$@"; IOS_DEVICE_ID="$2"; shift 2 ;;
    --team-id)
      require_arg "$@"; TEAM_ID="$2"; shift 2 ;;
    --vt-lib-dir)
      require_arg "$@"; VT_LIB_DIR="$2"; shift 2 ;;
    --terminal-body-impl)
      require_arg "$@"; TERMINAL_BODY_IMPL="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    --)
      shift; break ;;
    *)
      echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$ROOT_DIR/bench/generated/runtime-view-e2e/run-$(date +%Y%m%d-%H%M%S)"
elif [[ "$OUTPUT_DIR" != /* ]]; then
  OUTPUT_DIR="$ROOT_DIR/$OUTPUT_DIR"
fi
mkdir -p "$OUTPUT_DIR"
if [[ -n "$VT_LIB_DIR" ]]; then
  BOO_VT_LIB_DIR="$VT_LIB_DIR"
fi

WORKLOAD_DIR="$OUTPUT_DIR/workload"
DESKTOP_DIR="$OUTPUT_DIR/desktop"
IOS_DIR="$OUTPUT_DIR/ios"
CONFIG_ROOT="$OUTPUT_DIR/config"
SOCKET_PATH="$OUTPUT_DIR/boo-runtime-view-e2e.sock"
LOG_PATH="$DESKTOP_DIR/boo.log"
CARGO_BUILD_LOG="$DESKTOP_DIR/cargo-build.log"
mkdir -p "$WORKLOAD_DIR" "$DESKTOP_DIR" "$CONFIG_ROOT/boo"

cleanup() {
  local pid
  for pid in "${GUI_PID:-}" "${SERVER_PID:-}"; do
    if [[ -n "$pid" ]] && kill -0 "$pid" >/dev/null 2>&1; then
      kill "$pid" >/dev/null 2>&1 || true
      wait "$pid" >/dev/null 2>&1 || true
    fi
  done
  rm -f "$SOCKET_PATH" "${SOCKET_PATH}.stream"
}
trap cleanup EXIT

cd "$ROOT_DIR"
python3 scripts/gen-runtime-view-workload.py \
  --seed "$SEED" \
  --bytes "$BYTES_PER_PANE" \
  --profile runtime-view-e2e \
  --output-dir "$WORKLOAD_DIR" \
  --panes 4 >"$DESKTOP_DIR/workload-manifest.stdout.json"

cat > "$CONFIG_ROOT/boo/config.boo" <<EOF
control-socket = $SOCKET_PATH
font-family = JetBrains Mono
font-size = 18
keybind = ctrl+shift+t = new_tab
EOF

cargo build >"$CARGO_BUILD_LOG" 2>&1
rm -f "$SOCKET_PATH" "$LOG_PATH"
(
  export BOO_PROFILE=1
  export XDG_CONFIG_HOME="$CONFIG_ROOT"
  if [[ -n "$TERMINAL_BODY_IMPL" ]]; then
    export BOO_TERMINAL_BODY_IMPL="$TERMINAL_BODY_IMPL"
  fi
  boo_with_vt_lib_env target/debug/boo \
    --headless \
    --trace-filter boo::latency=info \
    >"$LOG_PATH" 2>&1
) &
SERVER_PID=$!

python3 scripts/ui-test-client.py --socket "$SOCKET_PATH" wait-ready --timeout 30 >"$DESKTOP_DIR/initial-snapshot.json"
python3 scripts/ui-test-client.py --socket "$SOCKET_PATH" request resize-viewport cols=80 rows=18 >"$DESKTOP_DIR/pre-gui-resize.json"

(
  export BOO_PROFILE=1
  export XDG_CONFIG_HOME="$CONFIG_ROOT"
  if [[ -n "$TERMINAL_BODY_IMPL" ]]; then
    export BOO_TERMINAL_BODY_IMPL="$TERMINAL_BODY_IMPL"
  fi
  boo_with_vt_lib_env target/debug/boo \
    --trace-filter boo::latency=info \
    gui \
    >>"$LOG_PATH" 2>&1
) &
GUI_PID=$!
sleep 0.5
if ! kill -0 "$GUI_PID" >/dev/null 2>&1; then
  echo "Boo GUI client exited before the runtime-view e2e scenario started; see $LOG_PATH" >&2
  cat "$LOG_PATH" >&2
  exit 1
fi

python3 - "$ROOT_DIR" "$SOCKET_PATH" "$WORKLOAD_DIR/manifest.json" "$DESKTOP_DIR" "$LOG_PATH" "$SEED" <<'PY'
from __future__ import annotations

import json
import re
import socket
import subprocess
import sys
import time
from pathlib import Path

root = Path(sys.argv[1])
socket_path = sys.argv[2]
manifest_path = Path(sys.argv[3])
out_dir = Path(sys.argv[4])
log_path = Path(sys.argv[5])
seed = int(sys.argv[6])
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
action_metrics = []
divider_drag_metric = None


def request(payload: dict, expect_ok: bool = True) -> dict:
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
        sock.connect(socket_path)
        sock.sendall(json.dumps(payload, ensure_ascii=False).encode("utf-8") + b"\n")
        data = b""
        while not data.endswith(b"\n"):
            chunk = sock.recv(65536)
            if not chunk:
                break
            data += chunk
    response = json.loads(data.decode("utf-8"))
    if expect_ok and response != {"ok": True}:
        raise RuntimeError(f"unexpected response for {payload}: {response}")
    return response


def measured(name: str, payload: dict, expect_ok: bool = True) -> dict:
    started = time.perf_counter()
    response = request(payload, expect_ok=expect_ok)
    elapsed_ms = (time.perf_counter() - started) * 1000.0
    action_metrics.append({"name": name, "elapsed_ms": round(elapsed_ms, 3), "payload": payload})
    return response


def snapshot(name: str) -> dict:
    last_response = None
    for _ in range(30):
        response = request({"cmd": "get-ui-snapshot"}, expect_ok=False)
        if "snapshot" in response:
            (out_dir / f"{name}.json").write_text(json.dumps(response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            return response["snapshot"]
        last_response = response
        time.sleep(0.1)
    (out_dir / f"{name}.error.json").write_text(json.dumps(last_response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    raise RuntimeError(f"get-ui-snapshot failed for {name}: {last_response}")


def state_snapshot(name: str) -> dict:
    last_response = None
    for _ in range(30):
        response = request({"cmd": "get-ui-runtime-state"}, expect_ok=False)
        if "state" in response:
            (out_dir / f"{name}.json").write_text(json.dumps(response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            return response["state"]
        last_response = response
        time.sleep(0.1)
    (out_dir / f"{name}.error.json").write_text(json.dumps(last_response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    raise RuntimeError(f"get-ui-runtime-state failed for {name}: {last_response}")


def text_snapshot(name: str) -> dict:
    last_response = None
    for _ in range(30):
        response = request({"cmd": "get-ui-text-snapshot"}, expect_ok=False)
        if "snapshot" in response:
            (out_dir / f"{name}.json").write_text(json.dumps(response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            return response["snapshot"]
        last_response = response
        time.sleep(0.1)
    (out_dir / f"{name}.error.json").write_text(json.dumps(last_response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    raise RuntimeError(f"get-ui-text-snapshot failed for {name}: {last_response}")


def wait_for(name: str, predicate, timeout: float = 10.0, interval: float = 0.1, getter=snapshot) -> dict:
    deadline = time.monotonic() + timeout
    last = None
    while time.monotonic() < deadline:
        last = getter(name)
        if predicate(last):
            return last
        time.sleep(interval)
    raise AssertionError(f"timed out waiting for {name}; last={json.dumps(last, ensure_ascii=False)[:4000]}")


def terminal_text(terminal: dict | None) -> str:
    if not terminal:
        return ""
    return "\n".join("".join((cell.get("text") or " ") for cell in row["cells"]).rstrip() for row in terminal["rows_data"])


def compact_terminal_text(text: str) -> str:
    return text.replace("\n", "")


def all_pane_text(snapshot_payload: dict) -> dict[int, str]:
    if "pane_texts" in snapshot_payload:
        return {int(item["pane_id"]): item.get("text", "") for item in snapshot_payload.get("pane_texts") or []}
    texts = {}
    for item in snapshot_payload.get("pane_terminals") or []:
        texts[int(item["pane_id"])] = terminal_text(item.get("terminal"))
    if snapshot_payload.get("terminal") and snapshot_payload.get("focused_pane") not in texts:
        texts[int(snapshot_payload["focused_pane"])] = terminal_text(snapshot_payload["terminal"])
    return texts


def pane_center(pane: dict) -> tuple[float, float]:
    frame = pane["frame"]
    return frame["x"] + frame["width"] / 2.0, frame["y"] + frame["height"] / 2.0


def mouse_event(event: dict) -> None:
    measured("mouse_event", {"cmd": "app-mouse-event", "event": event})


def click(x: float, y: float) -> None:
    mouse_event({"ButtonPressed": {"button": "Left", "x": x, "y": y, "mods": 0}})
    mouse_event({"ButtonReleased": {"button": "Left", "x": x, "y": y, "mods": 0}})


def drag(x1: float, y1: float, x2: float, y2: float) -> None:
    mouse_event({"ButtonPressed": {"button": "Left", "x": x1, "y": y1, "mods": 0}})
    mouse_event({"CursorMoved": {"x": x2, "y": y2, "mods": 0}})
    mouse_event({"ButtonReleased": {"button": "Left", "x": x2, "y": y2, "mods": 0}})


def send_file_to_focused(file_info: dict) -> dict:
    path = Path(file_info["path"])
    payload = path.read_text(encoding="utf-8")
    chunk_size = 16 * 1024
    started = time.perf_counter()
    sent_bytes = 0
    chunks = 0
    for offset in range(0, len(payload), chunk_size):
        chunk = payload[offset:offset + chunk_size]
        measured("send_vt_chunk", {"cmd": "send-vt", "text": chunk})
        sent_bytes += len(chunk.encode("utf-8"))
        chunks += 1
    elapsed = time.perf_counter() - started
    return {
        "pane_index": file_info["pane_index"],
        "path": str(path),
        "bytes": sent_bytes,
        "chunks": chunks,
        "elapsed_ms": round(elapsed * 1000.0, 3),
        "bytes_per_sec": round(sent_bytes / elapsed, 1) if elapsed > 0 else None,
        "end_marker": file_info["end_marker"],
    }


def assert_layout(snap: dict, tabs: int, active_tab: int, panes: int) -> None:
    assert len(snap["tabs"]) == tabs, snap["tabs"]
    assert snap["active_tab"] == active_tab, snap["active_tab"]
    assert len(snap["visible_panes"]) == panes, snap["visible_panes"]


snap = snapshot("initial")
assert_layout(snap, 1, 0, 1)
assert snap["tabs"][0]["pane_count"] == 1
snap = wait_for(
    "after-initial-resize",
    lambda s: (s.get("terminal") or {}).get("cols") == 80 and (s.get("terminal") or {}).get("rows") == 18,
)

# Tab 1 gets its own stream first, then the scenario returns to tab 2 at the end.
streams = []
streams.append(send_file_to_focused(manifest["files"][0]))
wait_for(
    "tab1-after-stream",
    lambda s: manifest["files"][0]["end_marker"] in compact_terminal_text("\n".join(all_pane_text(s).values())),
    timeout=12,
    getter=text_snapshot,
)

measured("new_tab", {"cmd": "new-tab"})
snap = wait_for("after-new-tab", lambda s: len(s["tabs"]) == 2 and s["active_tab"] == 1 and len(s["visible_panes"]) == 1, getter=state_snapshot)
assert snap["tabs"][0]["pane_count"] == 1 and snap["tabs"][1]["pane_count"] == 1

measured("new_split_right", {"cmd": "new-split", "direction": "right"})
snap = wait_for("after-split-right", lambda s: len(s["visible_panes"]) == 2 and s["tabs"][1]["pane_count"] == 2, getter=state_snapshot)
measured("new_split_down", {"cmd": "new-split", "direction": "down"})
snap = wait_for("after-split-down", lambda s: len(s["visible_panes"]) == 3 and s["tabs"][1]["pane_count"] == 3, getter=state_snapshot)
assert_layout(snap, 2, 1, 3)

# Stream deterministic output into each tab-2 pane by focusing pane centers.
tab2_streams = []
snap = state_snapshot("before-tab2-streams")
pane_targets = list(snap["visible_panes"])

# Exercise click focus for every visible pane before the high-throughput stream
# begins. This keeps focus verification deterministic even when later output
# temporarily starves UI snapshot replies.
for pane in pane_targets:
    x, y = pane_center(pane)
    started = time.perf_counter()
    click(x, y)
    focused = wait_for(
        f"click-focus-{pane['pane_id']}",
        lambda s, pid=pane["pane_id"]: s["focused_pane"] == pid,
        getter=state_snapshot,
    )
    action_metrics.append({
        "name": "click_focus_visible_pane",
        "pane_id": pane["pane_id"],
        "elapsed_ms": round((time.perf_counter() - started) * 1000.0, 3),
        "focused_pane": focused["focused_pane"],
    })

for file_info, target in zip(manifest["files"][1:], pane_targets):
    if not tab2_streams:
        state_snapshot(f"before-pane-{file_info['pane_index']}-stream")
    x, y = pane_center(target)
    measured("focus_pane", {"cmd": "focus-pane", "pane_id": target["pane_id"]})
    time.sleep(0.05)
    tab2_streams.append(send_file_to_focused(file_info))
streams.extend(tab2_streams)

snap = wait_for("after-all-streams", lambda s: len(s["visible_panes"]) == 3 and all(f["end_marker"] in compact_terminal_text("\n".join(all_pane_text(s).values())) for f in manifest["files"][1:]), timeout=60, getter=text_snapshot)
content_snapshot = snap
assert_layout(snap, 2, 1, 3)
assert any(tab["active"] and tab["index"] == 1 for tab in snap["tabs"])
assert all(tab["pane_count"] == expected for tab, expected in zip(snap["tabs"], [1, 3]))
all_visible_text = "\n".join(all_pane_text(snap).values())
assert "🙂" in all_visible_text and "測試" in all_visible_text.replace("\n", "").replace(" ", "")

before_drag = state_snapshot("before-divider-drag")
# Prefer the primary vertical divider between the left pane and right-side split.
panes = before_drag["visible_panes"]
left = min(panes, key=lambda p: p["frame"]["x"])
rightish = [p for p in panes if p["pane_id"] != left["pane_id"]]
divider_x = left["frame"]["x"] + left["frame"]["width"]
y_values = [p["frame"]["y"] + p["frame"]["height"] / 2.0 for p in rightish] or [left["frame"]["y"] + left["frame"]["height"] / 2.0]
divider_y = sum(y_values) / len(y_values)
old_width = left["frame"]["width"]
started = time.perf_counter()
drag(divider_x, divider_y, divider_x + 72.0, divider_y)
after_drag = wait_for("after-divider-drag", lambda s, pid=left["pane_id"], w=old_width: abs(next(p for p in s["visible_panes"] if p["pane_id"] == pid)["frame"]["width"] - w) >= 8.0, getter=state_snapshot)
divider_drag_metric = {
    "name": "divider_drag_resize",
    "elapsed_ms": round((time.perf_counter() - started) * 1000.0, 3),
    "pane_id": left["pane_id"],
    "before_width": round(old_width, 3),
    "after_width": round(next(p for p in after_drag["visible_panes"] if p["pane_id"] == left["pane_id"])["frame"]["width"], 3),
}
action_metrics.append(divider_drag_metric)

# Verify tab navigation still preserves the expected content and finish active on tab 2.
measured("prev_tab", {"cmd": "prev-tab"})
wait_for("after-prev-tab", lambda s: s["active_tab"] == 0 and len(s["visible_panes"]) == 1 and manifest["files"][0]["end_marker"] in compact_terminal_text("\n".join(all_pane_text(s).values())), timeout=12, getter=text_snapshot)
measured("next_tab", {"cmd": "next-tab"})
final = wait_for("final", lambda s: s["active_tab"] == 1 and len(s["tabs"]) == 2 and len(s["visible_panes"]) == 3, timeout=12, getter=state_snapshot)

# Let profile/trace buffers flush a little before summarizing the log.
time.sleep(0.5)
profile_summary = {"entries": []}
try:
    proc = subprocess.run(
        ["python3", str(root / "scripts/summarize-boo-profile.py"), str(log_path), "--paths", "client.canvas.draw", "client.stream.apply_delta", "client.view.render_terminal_scene", "--top", "12"],
        check=False,
        text=True,
        capture_output=True,
    )
    if proc.returncode == 0 and proc.stdout.strip():
        profile_summary = json.loads(proc.stdout)
except Exception as exc:  # best-effort summary; raw log remains an artifact
    profile_summary = {"error": str(exc), "entries": []}

trace_counts = {}
trace_elapsed = []
trace_re = re.compile(r"elapsed_ms=([0-9.]+)")
for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
    if "boo::latency" not in line and "remote." not in line:
        continue
    for event in ["remote.runtime_action", "remote.focus_pane", "remote.pane_update", "remote.render_apply", "remote.resize_split", "remote.set_viewed_tab"]:
        if event in line:
            trace_counts[event] = trace_counts.get(event, 0) + 1
    m = trace_re.search(line)
    if m:
        trace_elapsed.append(float(m.group(1)))

pane_texts = all_pane_text(content_snapshot)
missing = []
for file_info in manifest["files"][1:]:
    if file_info["end_marker"] not in compact_terminal_text("\n".join(pane_texts.values())):
        missing.append(file_info["end_marker"])
if missing:
    raise AssertionError(f"missing final tab2 markers: {missing}")

metrics = {
    "scenario": "runtime-view-e2e",
    "seed": seed,
    "bytes_per_pane_target": manifest["bytes_per_pane_target"],
    "workload": manifest,
    "latency": {
        "actions": action_metrics,
        "trace_event_counts": trace_counts,
        "trace_elapsed_ms": {
            "count": len(trace_elapsed),
            "max": round(max(trace_elapsed), 3) if trace_elapsed else None,
            "avg": round(sum(trace_elapsed) / len(trace_elapsed), 3) if trace_elapsed else None,
        },
    },
    "throughput": {
        "streams": streams,
        "total_bytes": sum(item["bytes"] for item in streams),
        "aggregate_bytes_per_sec": round(sum(item["bytes"] for item in streams) / max(sum(item["elapsed_ms"] for item in streams) / 1000.0, 0.001), 1),
    },
    "layout": {
        "tab_count": len(final["tabs"]),
        "active_tab": final["active_tab"],
        "tabs": final["tabs"],
        "visible_pane_count": len(final["visible_panes"]),
        "focused_pane": final["focused_pane"],
        "visible_panes": final["visible_panes"],
        "divider_drag": divider_drag_metric,
    },
    "profiler": profile_summary,
    "artifacts": {
        "log": str(log_path),
        "snapshots_dir": str(out_dir),
        "manifest": str(manifest_path),
    },
}
(out_dir / "metrics.json").write_text(json.dumps(metrics, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

summary = [
    "# Runtime View E2E Metrics Baseline",
    "",
    f"- seed: `{seed}`",
    f"- bytes per pane target: `{manifest['bytes_per_pane_target']}`",
    f"- tabs: `{metrics['layout']['tab_count']}`; active tab: `{metrics['layout']['active_tab'] + 1}`; visible panes: `{metrics['layout']['visible_pane_count']}`",
    f"- total streamed bytes: `{metrics['throughput']['total_bytes']}`",
    f"- aggregate control-stream throughput: `{metrics['throughput']['aggregate_bytes_per_sec']}` bytes/sec",
    f"- trace event counts: `{json.dumps(trace_counts, sort_keys=True)}`",
    "",
    "## Stream Throughput",
    "",
    "| pane stream | bytes | chunks | elapsed ms | bytes/sec |",
    "| --- | ---: | ---: | ---: | ---: |",
]
for item in streams:
    summary.append(f"| {item['pane_index']} | {item['bytes']} | {item['chunks']} | {item['elapsed_ms']} | {item['bytes_per_sec']} |")
summary.extend([
    "",
    "## Top BOO_PROFILE entries",
    "",
    "| path | kind | count | total ms | avg ms | max ms |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
])
for row in profile_summary.get("entries", [])[:12]:
    summary.append(f"| {row.get('path')} | {row.get('kind')} | {row.get('count')} | {row.get('total_ms')} | {row.get('avg_ms')} | {row.get('max_ms')} |")
(out_dir / "summary.md").write_text("\n".join(summary) + "\n", encoding="utf-8")

qos = [
    "# Runtime View QoS Baseline Candidates",
    "",
    "This is a baseline-only report. No runtime QoS scheduling or local prediction changes were made.",
    "",
    "## Observed Baseline",
    "",
    f"- Streamed `{metrics['throughput']['total_bytes']}` bytes across tab 1 plus three tab-2 panes.",
    f"- Final layout: `{metrics['layout']['tab_count']}` tabs, active tab `{metrics['layout']['active_tab'] + 1}`, `{metrics['layout']['visible_pane_count']}` visible panes.",
    f"- Trace counts: `{json.dumps(trace_counts, sort_keys=True)}`.",
    f"- Action latency samples: `{len(action_metrics)}`.",
    "",
    "## Candidate Strategies for the Next Pass",
    "",
    "1. Focused-pane priority under high output: prioritize runtime/apply work for the focused pane when multiple visible panes are producing output.",
    "2. Non-focused pane coalescing window: batch non-focused pane updates over a short bounded interval to reduce render/apply churn.",
    "3. Starvation guard for visible non-focused panes: cap coalescing delay so visible panes continue to advance predictably.",
    "4. Render/apply batching thresholds: use measured byte/update rates to choose when to batch deltas versus applying immediately.",
    "",
    "## Follow-up Data to Review",
    "",
    "- `metrics.json` latency action samples and trace event counts.",
    "- `summary.md` stream throughput and BOO_PROFILE hot paths.",
    "- `boo.log` raw `boo::latency` and `boo_profile` lines.",
]
(out_dir / "qos-baseline.md").write_text("\n".join(qos) + "\n", encoding="utf-8")
print(json.dumps({"ok": True, "metrics": str(out_dir / "metrics.json"), "summary": str(out_dir / "summary.md"), "qos": str(out_dir / "qos-baseline.md")}, indent=2))
PY

# Stop the desktop app before optional iOS work; artifacts are already flushed.
cleanup
GUI_PID=""
SERVER_PID=""

python3 - "$DESKTOP_DIR/metrics.json" <<'PY'
import json, sys
path = sys.argv[1]
with open(path, encoding='utf-8') as f:
    payload = json.load(f)
assert payload['scenario'] == 'runtime-view-e2e'
assert payload['layout']['tab_count'] == 2
assert payload['layout']['active_tab'] == 1
assert payload['layout']['visible_pane_count'] == 3
assert payload['throughput']['total_bytes'] > 0
print(f"desktop runtime-view-e2e metrics passed: {path}")
PY

if [[ "$DESKTOP_ONLY" != "1" && -n "$IOS_DEVICE_ID" ]]; then
  mkdir -p "$IOS_DIR"
  IOS_ARGS=(--device-id "$IOS_DEVICE_ID" --output-dir "$IOS_DIR" --scenario runtime-view-e2e --trace-actions focus-pane,set-viewed-tab,input --trace-input-command "cat <<'EOF'
$(python3 - <<PY
from pathlib import Path
text = Path('$WORKLOAD_DIR/pane-2.txt').read_text(encoding='utf-8')
print(text[-4096:].replace('\\r', ''))
PY
)
EOF")
  if [[ -n "$TEAM_ID" ]]; then
    IOS_ARGS+=(--team-id "$TEAM_ID")
  fi
  if [[ -n "$VT_LIB_DIR" ]]; then
    IOS_ARGS+=(--vt-lib-dir "$VT_LIB_DIR")
  fi
  bash scripts/verify-ios-signposts.sh "${IOS_ARGS[@]}"
fi

cat <<EOF
runtime-view-e2e baseline artifacts:
  output: $OUTPUT_DIR
  metrics: $DESKTOP_DIR/metrics.json
  summary: $DESKTOP_DIR/summary.md
  qos: $DESKTOP_DIR/qos-baseline.md
EOF
