#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOO_REPO_ROOT="$ROOT_DIR"
source "$ROOT_DIR/scripts/lib/vt-dylib-env.sh"

usage() {
  cat <<'EOF'
Usage: bash scripts/test-runtime-view-e2e-metrics.sh [options]

Runs the deterministic runtime-view e2e metrics baseline. The desktop lane
creates 2 tabs, splits tab 2 into 3 panes, streams generated unicode/emoji
terminal output, exercises focus/tab/statusbar/resize interactions, and writes
metrics artifacts. The iOS lane reuses the real-device signpost verifier with
runtime-view-e2e inputs when --ios-device-id is supplied.

Options:
  --seed N                 deterministic workload seed (default: 42)
  --bytes-per-pane N       generated bytes per stream/pane (default: 1048576)
  --output-dir PATH        artifacts directory (default: bench/generated/runtime-view-e2e/run-<timestamp>)
  --two-client             keep macOS GUI and a real iPad connected to one macOS server
  --desktop-only           skip the iOS lane even if device flags are present
  --ios-device-id UDID     run real-device signpost verification lane
  --team-id TEAM_ID        development team for iOS device build/signing
  --host HOST              host/IP advertised to the iOS device in --two-client mode
  --port PORT              remote daemon port used in --two-client mode
  --ios-time-limit DURATION xctrace duration for iOS lane (default: 24s)
  --vt-lib-dir PATH
  --terminal-body-impl NAME
  -h, --help
EOF
}

require_arg() {
  if [[ $# -lt 2 ]]; then
    echo "Missing value for $1" >&2
    usage >&2
    exit 2
  fi
}

SEED=42
BYTES_PER_PANE=1048576
OUTPUT_DIR=""
TWO_CLIENT=0
DESKTOP_ONLY=0
IOS_DEVICE_ID=""
TEAM_ID=""
HOST=""
REMOTE_PORT=""
IOS_TIME_LIMIT="24s"
VT_LIB_DIR="${BOO_VT_LIB_DIR:-${VT_LIB_DIR:-}}"
TERMINAL_BODY_IMPL="${BOO_TERMINAL_BODY_IMPL:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed)
      require_arg "$@"; SEED="$2"; shift 2 ;;
    --bytes-per-pane)
      require_arg "$@"; BYTES_PER_PANE="$2"; shift 2 ;;
    --output-dir)
      require_arg "$@"; OUTPUT_DIR="$2"; shift 2 ;;
    --two-client)
      TWO_CLIENT=1; shift ;;
    --desktop-only)
      DESKTOP_ONLY=1; shift ;;
    --ios-device-id)
      require_arg "$@"; IOS_DEVICE_ID="$2"; shift 2 ;;
    --team-id)
      require_arg "$@"; TEAM_ID="$2"; shift 2 ;;
    --host)
      require_arg "$@"; HOST="$2"; shift 2 ;;
    --port)
      require_arg "$@"; REMOTE_PORT="$2"; shift 2 ;;
    --ios-time-limit)
      require_arg "$@"; IOS_TIME_LIMIT="$2"; shift 2 ;;
    --vt-lib-dir)
      require_arg "$@"; VT_LIB_DIR="$2"; shift 2 ;;
    --terminal-body-impl)
      require_arg "$@"; TERMINAL_BODY_IMPL="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    --)
      shift; break ;;
    *)
      echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$ROOT_DIR/bench/generated/runtime-view-e2e/run-$(date +%Y%m%d-%H%M%S)"
elif [[ "$OUTPUT_DIR" != /* ]]; then
  OUTPUT_DIR="$ROOT_DIR/$OUTPUT_DIR"
fi
mkdir -p "$OUTPUT_DIR"
if [[ -n "$VT_LIB_DIR" ]]; then
  BOO_VT_LIB_DIR="$VT_LIB_DIR"
fi

if [[ "$TWO_CLIENT" == "1" ]]; then
  if [[ "$DESKTOP_ONLY" == "1" ]]; then
    echo "--two-client cannot be combined with --desktop-only" >&2
    exit 2
  fi
  if [[ -z "$IOS_DEVICE_ID" ]]; then
    echo "--two-client requires --ios-device-id" >&2
    exit 2
  fi
  if [[ -z "$HOST" ]]; then
    HOST="$(ifconfig en0 | awk '/inet / { print $2; exit }')"
  fi
  if [[ -z "$HOST" ]]; then
    echo "Could not determine host address for the iOS device; pass --host" >&2
    exit 2
  fi
  if [[ -z "$REMOTE_PORT" ]]; then
    REMOTE_PORT="$(
      python3 -c 'import socket; s = socket.socket(); s.bind(("0.0.0.0", 0)); print(s.getsockname()[1]); s.close()'
    )"
  fi
fi

WORKLOAD_DIR="$OUTPUT_DIR/workload"
DESKTOP_DIR="$OUTPUT_DIR/desktop"
IOS_DIR="$OUTPUT_DIR/ios"
CONFIG_ROOT="$OUTPUT_DIR/config"
SOCKET_PATH="$OUTPUT_DIR/boo-runtime-view-e2e.sock"
GUI_TEST_SOCKET="$OUTPUT_DIR/boo-runtime-view-e2e-gui.sock"
LOG_PATH="$DESKTOP_DIR/boo.log"
CARGO_BUILD_LOG="$DESKTOP_DIR/cargo-build.log"
mkdir -p "$WORKLOAD_DIR" "$DESKTOP_DIR" "$CONFIG_ROOT/boo"

cleanup() {
  local pid
  for pid in "${IOS_VERIFY_PID:-}" "${GUI_PID:-}" "${SERVER_PID:-}"; do
    if [[ -n "$pid" ]] && kill -0 "$pid" >/dev/null 2>&1; then
      kill "$pid" >/dev/null 2>&1 || true
      wait "$pid" >/dev/null 2>&1 || true
    fi
  done
  rm -f "$SOCKET_PATH" "${SOCKET_PATH}.stream" "$GUI_TEST_SOCKET"
}
trap cleanup EXIT

cd "$ROOT_DIR"
python3 scripts/gen-runtime-view-workload.py \
  --seed "$SEED" \
  --bytes "$BYTES_PER_PANE" \
  --profile runtime-view-e2e \
  --output-dir "$WORKLOAD_DIR" \
  --panes 4 >"$DESKTOP_DIR/workload-manifest.stdout.json"

cat > "$CONFIG_ROOT/boo/config.boo" <<EOF
control-socket = $SOCKET_PATH
font-family = JetBrains Mono
font-size = 18
keybind = ctrl+shift+t = new_tab
EOF

cargo build >"$CARGO_BUILD_LOG" 2>&1
rm -f "$SOCKET_PATH" "$GUI_TEST_SOCKET" "$LOG_PATH"
(
  export XDG_CONFIG_HOME="$CONFIG_ROOT"
  if [[ -n "$TERMINAL_BODY_IMPL" ]]; then
    export BOO_TERMINAL_BODY_IMPL="$TERMINAL_BODY_IMPL"
  fi
  if [[ "$TWO_CLIENT" == "1" ]]; then
    boo_with_vt_lib_env target/debug/boo \
      --profiling \
      --trace-filter boo::latency=info \
      server \
      --socket "$SOCKET_PATH" \
      --remote-port "$REMOTE_PORT" \
      --remote-bind-address 0.0.0.0 \
      >"$LOG_PATH" 2>&1
  else
    boo_with_vt_lib_env target/debug/boo \
      --profiling \
      --headless \
      --trace-filter boo::latency=info \
      >"$LOG_PATH" 2>&1
  fi
) &
SERVER_PID=$!

python3 scripts/ui-test-client.py --socket "$SOCKET_PATH" wait-ready --timeout 30 >"$DESKTOP_DIR/initial-snapshot.json"
python3 scripts/ui-test-client.py --socket "$SOCKET_PATH" request resize-viewport cols=80 rows=18 >"$DESKTOP_DIR/pre-gui-resize.json"

(
  export XDG_CONFIG_HOME="$CONFIG_ROOT"
  export BOO_GUI_TEST_SOCKET="$GUI_TEST_SOCKET"
  if [[ -n "$TERMINAL_BODY_IMPL" ]]; then
    export BOO_TERMINAL_BODY_IMPL="$TERMINAL_BODY_IMPL"
  fi
  boo_with_vt_lib_env target/debug/boo \
    --profiling \
    --trace-filter boo::latency=info \
    gui \
    >>"$LOG_PATH" 2>&1
) &
GUI_PID=$!
sleep 0.5
if ! kill -0 "$GUI_PID" >/dev/null 2>&1; then
  echo "Boo GUI client exited before the runtime-view e2e scenario started; see $LOG_PATH" >&2
  cat "$LOG_PATH" >&2
  exit 1
fi
python3 scripts/ui-test-client.py --socket "$SOCKET_PATH" request resize-viewport cols=80 rows=18 >"$DESKTOP_DIR/post-gui-resize.json"

python3 - "$ROOT_DIR" "$SOCKET_PATH" "$WORKLOAD_DIR/manifest.json" "$DESKTOP_DIR" "$LOG_PATH" "$SEED" <<'PY'
from __future__ import annotations

import json
import re
import socket
import subprocess
import sys
import time
from pathlib import Path

root = Path(sys.argv[1])
socket_path = sys.argv[2]
manifest_path = Path(sys.argv[3])
out_dir = Path(sys.argv[4])
log_path = Path(sys.argv[5])
seed = int(sys.argv[6])
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
action_metrics = []
divider_drag_metric = None


def request(payload: dict, expect_ok: bool = True) -> dict:
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
        sock.connect(socket_path)
        sock.sendall(json.dumps(payload, ensure_ascii=False).encode("utf-8") + b"\n")
        data = b""
        while not data.endswith(b"\n"):
            chunk = sock.recv(65536)
            if not chunk:
                break
            data += chunk
    response = json.loads(data.decode("utf-8"))
    if expect_ok and response != {"ok": True}:
        raise RuntimeError(f"unexpected response for {payload}: {response}")
    return response


def measured(name: str, payload: dict, expect_ok: bool = True) -> dict:
    started = time.perf_counter()
    response = request(payload, expect_ok=expect_ok)
    elapsed_ms = (time.perf_counter() - started) * 1000.0
    action_metrics.append({"name": name, "elapsed_ms": round(elapsed_ms, 3), "payload": payload})
    return response


def percentile(values, p):
    if not values:
        return None
    sorted_values = sorted(values)
    idx = int(round((len(sorted_values) - 1) * p))
    return round(sorted_values[idx], 3)


def summarize_ms(values):
    return {
        "count": len(values),
        "min": round(min(values), 3) if values else None,
        "p50": percentile(values, 0.50),
        "p90": percentile(values, 0.90),
        "p99": percentile(values, 0.99),
        "max": round(max(values), 3) if values else None,
        "avg": round(sum(values) / len(values), 3) if values else None,
    }


def measure_noop_roundtrip(name: str, samples: int = 24) -> dict:
    values = []
    for _ in range(samples):
        started = time.perf_counter()
        request({"cmd": "ping"})
        values.append((time.perf_counter() - started) * 1000.0)
    return {
        "name": name,
        "route": "desktop-control-socket",
        "operation": "ping",
        "elapsed_ms": summarize_ms(values),
        "samples": [round(value, 3) for value in values],
    }


def snapshot(name: str) -> dict:
    last_response = None
    for _ in range(30):
        response = request({"cmd": "get-ui-snapshot"}, expect_ok=False)
        if "snapshot" in response:
            (out_dir / f"{name}.json").write_text(json.dumps(response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            return response["snapshot"]
        last_response = response
        time.sleep(0.1)
    (out_dir / f"{name}.error.json").write_text(json.dumps(last_response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    raise RuntimeError(f"get-ui-snapshot failed for {name}: {last_response}")


def state_snapshot(name: str) -> dict:
    last_response = None
    for _ in range(30):
        response = request({"cmd": "get-ui-runtime-state"}, expect_ok=False)
        if "state" in response:
            (out_dir / f"{name}.json").write_text(json.dumps(response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            return response["state"]
        last_response = response
        time.sleep(0.1)
    (out_dir / f"{name}.error.json").write_text(json.dumps(last_response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    raise RuntimeError(f"get-ui-runtime-state failed for {name}: {last_response}")


def text_snapshot(name: str) -> dict:
    last_response = None
    for _ in range(30):
        response = request({"cmd": "get-ui-text-snapshot"}, expect_ok=False)
        if "snapshot" in response:
            (out_dir / f"{name}.json").write_text(json.dumps(response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            return response["snapshot"]
        last_response = response
        time.sleep(0.1)
    (out_dir / f"{name}.error.json").write_text(json.dumps(last_response, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    raise RuntimeError(f"get-ui-text-snapshot failed for {name}: {last_response}")


def wait_for(name: str, predicate, timeout: float = 10.0, interval: float = 0.1, getter=snapshot) -> dict:
    deadline = time.monotonic() + timeout
    last = None
    while time.monotonic() < deadline:
        last = getter(name)
        if predicate(last):
            return last
        time.sleep(interval)
    raise AssertionError(f"timed out waiting for {name}; last={json.dumps(last, ensure_ascii=False)[:4000]}")


def terminal_text(terminal: dict | None) -> str:
    if not terminal:
        return ""
    return "\n".join("".join((cell.get("text") or " ") for cell in row["cells"]).rstrip() for row in terminal["rows_data"])


def compact_terminal_text(text: str) -> str:
    return text.replace("\n", "")


def all_pane_text(snapshot_payload: dict) -> dict[int, str]:
    if "pane_texts" in snapshot_payload:
        return {int(item["pane_id"]): item.get("text", "") for item in snapshot_payload.get("pane_texts") or []}
    texts = {}
    for item in snapshot_payload.get("pane_terminals") or []:
        texts[int(item["pane_id"])] = terminal_text(item.get("terminal"))
    if snapshot_payload.get("terminal") and snapshot_payload.get("focused_pane") not in texts:
        texts[int(snapshot_payload["focused_pane"])] = terminal_text(snapshot_payload["terminal"])
    return texts


def pane_center(pane: dict) -> tuple[float, float]:
    frame = pane["frame"]
    return frame["x"] + frame["width"] / 2.0, frame["y"] + frame["height"] / 2.0


def mouse_event(event: dict) -> None:
    measured("mouse_event", {"cmd": "app-mouse-event", "event": event})


def click(x: float, y: float) -> None:
    mouse_event({"ButtonPressed": {"button": "Left", "x": x, "y": y, "mods": 0}})
    mouse_event({"ButtonReleased": {"button": "Left", "x": x, "y": y, "mods": 0}})


def drag(x1: float, y1: float, x2: float, y2: float) -> None:
    mouse_event({"ButtonPressed": {"button": "Left", "x": x1, "y": y1, "mods": 0}})
    mouse_event({"CursorMoved": {"x": x2, "y": y2, "mods": 0}})
    mouse_event({"ButtonReleased": {"button": "Left", "x": x2, "y": y2, "mods": 0}})


def send_file_to_focused(file_info: dict) -> dict:
    path = Path(file_info["path"])
    payload = path.read_text(encoding="utf-8")
    chunk_size = 16 * 1024
    started = time.perf_counter()
    sent_bytes = 0
    chunks = 0
    for offset in range(0, len(payload), chunk_size):
        chunk = payload[offset:offset + chunk_size]
        measured("send_vt_chunk", {"cmd": "send-vt", "text": chunk})
        sent_bytes += len(chunk.encode("utf-8"))
        chunks += 1
    elapsed = time.perf_counter() - started
    return {
        "pane_index": file_info["pane_index"],
        "path": str(path),
        "bytes": sent_bytes,
        "chunks": chunks,
        "elapsed_ms": round(elapsed * 1000.0, 3),
        "bytes_per_sec": round(sent_bytes / elapsed, 1) if elapsed > 0 else None,
        "end_marker": file_info["end_marker"],
    }


def assert_layout(snap: dict, tabs: int, active_tab: int, panes: int) -> None:
    assert len(snap["tabs"]) == tabs, snap["tabs"]
    assert snap["active_tab"] == active_tab, snap["active_tab"]
    assert len(snap["visible_panes"]) == panes, snap["visible_panes"]


def ensure_active_tab(index: int) -> dict:
    for _ in range(4):
        snap = state_snapshot("ensure-active-tab")
        if snap["active_tab"] == index:
            return snap
        measured("next_tab", {"cmd": "next-tab"})
        time.sleep(0.1)
    snap = state_snapshot("ensure-active-tab-final")
    if snap["active_tab"] != index:
        raise AssertionError(f"failed to activate tab index {index}; last={json.dumps(snap, ensure_ascii=False)[:4000]}")
    return snap


def visible_pane_by_id(snap: dict, pane_id: int) -> dict:
    for pane in snap["visible_panes"]:
        if pane["pane_id"] == pane_id:
            return pane
    raise AssertionError(f"pane {pane_id} not visible in snapshot {snap}")


noop_before = measure_noop_roundtrip("control_ping_before_layout")

snap = snapshot("initial")
assert_layout(snap, 1, 0, 1)
assert snap["tabs"][0]["pane_count"] == 1
snap = wait_for(
    "after-initial-resize",
    lambda s: (s.get("terminal") or {}).get("cols", 0) >= 80 and (s.get("terminal") or {}).get("rows", 0) >= 18,
)

# Tab 1 gets its own stream first, then the scenario returns to tab 2 at the end.
streams = []
streams.append(send_file_to_focused(manifest["files"][0]))
wait_for(
    "tab1-after-stream",
    lambda s: manifest["files"][0]["end_marker"] in compact_terminal_text("\n".join(all_pane_text(s).values())),
    timeout=12,
    getter=text_snapshot,
)

measured("new_tab", {"cmd": "new-tab"})
snap = wait_for("after-new-tab", lambda s: len(s["tabs"]) == 2 and s["active_tab"] == 1 and len(s["visible_panes"]) == 1, getter=state_snapshot)
assert snap["tabs"][0]["pane_count"] == 1 and snap["tabs"][1]["pane_count"] == 1

measured("new_split_right", {"cmd": "new-split", "direction": "right"})
snap = wait_for("after-split-right", lambda s: len(s["visible_panes"]) == 2 and s["tabs"][1]["pane_count"] == 2, getter=state_snapshot)
measured("new_split_down", {"cmd": "new-split", "direction": "down"})
snap = wait_for("after-split-down", lambda s: len(s["visible_panes"]) == 3 and s["tabs"][1]["pane_count"] == 3, getter=state_snapshot)
assert_layout(snap, 2, 1, 3)

# Stream deterministic output into each tab-2 pane by focusing pane centers.
tab2_streams = []
snap = state_snapshot("before-tab2-streams")
pane_target_ids = [pane["pane_id"] for pane in snap["visible_panes"]]

# Exercise click focus for every visible pane before the high-throughput stream
# begins. This keeps focus verification deterministic even when later output
# temporarily starves UI snapshot replies.
for pane_id in pane_target_ids:
    started = time.perf_counter()
    focused = None
    click_reflected = False
    for _ in range(3):
        snap = ensure_active_tab(1)
        pane = visible_pane_by_id(snap, pane_id)
        x, y = pane_center(pane)
        click(x, y)
        try:
            focused = wait_for(
                f"click-focus-{pane_id}",
                lambda s, pid=pane_id: s["active_tab"] == 1 and s["focused_pane"] == pid,
                timeout=3,
                getter=state_snapshot,
            )
            click_reflected = True
            break
        except AssertionError:
            continue
    if focused is None:
        measured("focus_pane_after_click_fallback", {"cmd": "focus-pane", "pane_id": pane_id})
        focused = wait_for(
            f"click-focus-fallback-{pane_id}",
            lambda s, pid=pane_id: s["active_tab"] == 1 and s["focused_pane"] == pid,
            getter=state_snapshot,
        )
    action_metrics.append({
        "name": "click_focus_visible_pane",
        "pane_id": pane_id,
        "elapsed_ms": round((time.perf_counter() - started) * 1000.0, 3),
        "focused_pane": focused["focused_pane"],
        "click_reflected": click_reflected,
    })

for file_info, pane_id in zip(manifest["files"][1:], pane_target_ids):
    if not tab2_streams:
        state_snapshot(f"before-pane-{file_info['pane_index']}-stream")
    ensure_active_tab(1)
    measured("focus_pane", {"cmd": "focus-pane", "pane_id": pane_id})
    time.sleep(0.05)
    tab2_streams.append(send_file_to_focused(file_info))
streams.extend(tab2_streams)

snap = wait_for("after-all-streams", lambda s: len(s["visible_panes"]) == 3 and all(f["end_marker"] in compact_terminal_text("\n".join(all_pane_text(s).values())) for f in manifest["files"][1:]), timeout=60, getter=text_snapshot)
content_snapshot = snap
assert_layout(snap, 2, 1, 3)
assert any(tab["active"] and tab["index"] == 1 for tab in snap["tabs"])
assert all(tab["pane_count"] == expected for tab, expected in zip(snap["tabs"], [1, 3]))
all_visible_text = "\n".join(all_pane_text(snap).values())
assert "🙂" in all_visible_text and "測試" in all_visible_text.replace("\n", "").replace(" ", "")

before_drag = state_snapshot("before-divider-drag")
# Prefer the primary vertical divider between the left pane and right-side split.
panes = before_drag["visible_panes"]
left = min(panes, key=lambda p: p["frame"]["x"])
rightish = [p for p in panes if p["pane_id"] != left["pane_id"]]
divider_x = left["frame"]["x"] + left["frame"]["width"]
y_values = [p["frame"]["y"] + p["frame"]["height"] / 2.0 for p in rightish] or [left["frame"]["y"] + left["frame"]["height"] / 2.0]
divider_y = sum(y_values) / len(y_values)
old_width = left["frame"]["width"]
started = time.perf_counter()
drag(divider_x, divider_y, divider_x + 72.0, divider_y)
after_drag = wait_for("after-divider-drag", lambda s, pid=left["pane_id"], w=old_width: abs(next(p for p in s["visible_panes"] if p["pane_id"] == pid)["frame"]["width"] - w) >= 8.0, getter=state_snapshot)
divider_drag_metric = {
    "name": "divider_drag_resize",
    "elapsed_ms": round((time.perf_counter() - started) * 1000.0, 3),
    "pane_id": left["pane_id"],
    "before_width": round(old_width, 3),
    "after_width": round(next(p for p in after_drag["visible_panes"] if p["pane_id"] == left["pane_id"])["frame"]["width"], 3),
}
action_metrics.append(divider_drag_metric)

# Verify tab navigation still preserves the expected content and finish active on tab 2.
measured("prev_tab", {"cmd": "prev-tab"})
wait_for("after-prev-tab", lambda s: s["active_tab"] == 0 and len(s["visible_panes"]) == 1 and manifest["files"][0]["end_marker"] in compact_terminal_text("\n".join(all_pane_text(s).values())), timeout=12, getter=text_snapshot)
measured("next_tab", {"cmd": "next-tab"})
final = wait_for("final", lambda s: s["active_tab"] == 1 and len(s["tabs"]) == 2 and len(s["visible_panes"]) == 3, timeout=12, getter=state_snapshot)

# Let profile/trace buffers flush a little before summarizing the log.
noop_after = measure_noop_roundtrip("control_ping_after_streams")
time.sleep(0.5)
profile_summary = {"entries": []}
try:
    proc = subprocess.run(
        ["python3", str(root / "scripts/summarize-boo-profile.py"), str(log_path), "--paths", "client.canvas.draw", "client.stream.apply_delta", "client.view.render_terminal_scene", "--top", "12"],
        check=False,
        text=True,
        capture_output=True,
    )
    if proc.returncode == 0 and proc.stdout.strip():
        profile_summary = json.loads(proc.stdout)
except Exception as exc:  # best-effort summary; raw log remains an artifact
    profile_summary = {"error": str(exc), "entries": []}

trace_counts = {}
trace_elapsed = []
trace_re = re.compile(r"elapsed_ms=([0-9.]+)")
for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
    if "boo::latency" not in line and "remote." not in line:
        continue
    for event in ["remote.runtime_action", "remote.focus_pane", "remote.pane_update", "remote.render_apply", "remote.resize_split", "remote.set_viewed_tab", "remote.heartbeat_rtt"]:
        if event in line:
            trace_counts[event] = trace_counts.get(event, 0) + 1
    m = trace_re.search(line)
    if m:
        trace_elapsed.append(float(m.group(1)))

pane_texts = all_pane_text(content_snapshot)
missing = []
for file_info in manifest["files"][1:]:
    if file_info["end_marker"] not in compact_terminal_text("\n".join(pane_texts.values())):
        missing.append(file_info["end_marker"])
if missing:
    raise AssertionError(f"missing final tab2 markers: {missing}")

metrics = {
    "scenario": "runtime-view-e2e",
    "seed": seed,
    "bytes_per_pane_target": manifest["bytes_per_pane_target"],
    "workload": manifest,
    "latency": {
        "actions": action_metrics,
        "base_noop_roundtrip": [noop_before, noop_after],
        "trace_event_counts": trace_counts,
        "trace_elapsed_ms": {
            "count": len(trace_elapsed),
            "max": round(max(trace_elapsed), 3) if trace_elapsed else None,
            "avg": round(sum(trace_elapsed) / len(trace_elapsed), 3) if trace_elapsed else None,
        },
    },
    "throughput": {
        "streams": streams,
        "total_bytes": sum(item["bytes"] for item in streams),
        "aggregate_bytes_per_sec": round(sum(item["bytes"] for item in streams) / max(sum(item["elapsed_ms"] for item in streams) / 1000.0, 0.001), 1),
    },
    "layout": {
        "tab_count": len(final["tabs"]),
        "active_tab": final["active_tab"],
        "tabs": final["tabs"],
        "visible_pane_count": len(final["visible_panes"]),
        "focused_pane": final["focused_pane"],
        "visible_panes": final["visible_panes"],
        "divider_drag": divider_drag_metric,
    },
    "profiler": profile_summary,
    "artifacts": {
        "log": str(log_path),
        "snapshots_dir": str(out_dir),
        "manifest": str(manifest_path),
    },
}
(out_dir / "metrics.json").write_text(json.dumps(metrics, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

summary = [
    "# Runtime View E2E Metrics Baseline",
    "",
    f"- seed: `{seed}`",
    f"- bytes per pane target: `{manifest['bytes_per_pane_target']}`",
    f"- tabs: `{metrics['layout']['tab_count']}`; active tab: `{metrics['layout']['active_tab'] + 1}`; visible panes: `{metrics['layout']['visible_pane_count']}`",
    f"- total streamed bytes: `{metrics['throughput']['total_bytes']}`",
    f"- aggregate control-stream throughput: `{metrics['throughput']['aggregate_bytes_per_sec']}` bytes/sec",
    f"- base no-op RTT before layout: `{noop_before['elapsed_ms']['avg']}` ms avg, p50 `{noop_before['elapsed_ms']['p50']}` ms",
    f"- base no-op RTT after streams: `{noop_after['elapsed_ms']['avg']}` ms avg, p50 `{noop_after['elapsed_ms']['p50']}` ms",
    f"- trace event counts: `{json.dumps(trace_counts, sort_keys=True)}`",
    "",
    "## Stream Throughput",
    "",
    "| pane stream | bytes | chunks | elapsed ms | bytes/sec |",
    "| --- | ---: | ---: | ---: | ---: |",
]
for item in streams:
    summary.append(f"| {item['pane_index']} | {item['bytes']} | {item['chunks']} | {item['elapsed_ms']} | {item['bytes_per_sec']} |")
summary.extend([
    "",
    "## Top built-in --profiling entries",
    "",
    "| path | kind | count | total ms | avg ms | max ms |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
])
for row in profile_summary.get("entries", [])[:12]:
    summary.append(f"| {row.get('path')} | {row.get('kind')} | {row.get('count')} | {row.get('total_ms')} | {row.get('avg_ms')} | {row.get('max_ms')} |")
(out_dir / "summary.md").write_text("\n".join(summary) + "\n", encoding="utf-8")

qos = [
    "# Runtime View QoS Baseline Candidates",
    "",
    "This is a baseline-only report. No runtime QoS scheduling or local prediction changes were made.",
    "",
    "## Observed Baseline",
    "",
    f"- Streamed `{metrics['throughput']['total_bytes']}` bytes across tab 1 plus three tab-2 panes.",
    f"- Final layout: `{metrics['layout']['tab_count']}` tabs, active tab `{metrics['layout']['active_tab'] + 1}`, `{metrics['layout']['visible_pane_count']}` visible panes.",
    f"- Trace counts: `{json.dumps(trace_counts, sort_keys=True)}`.",
    f"- Action latency samples: `{len(action_metrics)}`.",
    "",
    "## Candidate Strategies for the Next Pass",
    "",
    "1. Focused-pane priority under high output: prioritize runtime/apply work for the focused pane when multiple visible panes are producing output.",
    "2. Non-focused pane coalescing window: batch non-focused pane updates over a short bounded interval to reduce render/apply churn.",
    "3. Starvation guard for visible non-focused panes: cap coalescing delay so visible panes continue to advance predictably.",
    "4. Render/apply batching thresholds: use measured byte/update rates to choose when to batch deltas versus applying immediately.",
    "",
    "## Follow-up Data to Review",
    "",
    "- `metrics.json` latency action samples and trace event counts.",
    "- `summary.md` stream throughput and built-in `--profiling` hot paths.",
    "- `boo.log` raw `boo::latency` and `boo_profile` lines.",
]
(out_dir / "qos-baseline.md").write_text("\n".join(qos) + "\n", encoding="utf-8")
print(json.dumps({"ok": True, "metrics": str(out_dir / "metrics.json"), "summary": str(out_dir / "summary.md"), "qos": str(out_dir / "qos-baseline.md")}, indent=2))
PY

# Stop the desktop app before the legacy iOS signpost lane; the two-client lane
# keeps both desktop processes alive so iPad and macOS are subscribed together.
if [[ "$TWO_CLIENT" != "1" ]]; then
  cleanup
  GUI_PID=""
  SERVER_PID=""
fi

python3 - "$DESKTOP_DIR/metrics.json" <<'PY'
import json, sys
path = sys.argv[1]
with open(path, encoding='utf-8') as f:
    payload = json.load(f)
assert payload['scenario'] == 'runtime-view-e2e'
assert payload['layout']['tab_count'] == 2
assert payload['layout']['active_tab'] == 1
assert payload['layout']['visible_pane_count'] == 3
assert payload['throughput']['total_bytes'] > 0
print(f"desktop runtime-view-e2e metrics passed: {path}")
PY

if [[ "$TWO_CLIENT" == "1" ]]; then
  mkdir -p "$IOS_DIR"
  python3 - "$GUI_TEST_SOCKET" "$DESKTOP_DIR/final.json" <<'PY'
import json
import socket
import sys
import time
from pathlib import Path

socket_path = sys.argv[1]
final_path = Path(sys.argv[2])
final = json.loads(final_path.read_text(encoding="utf-8"))["state"]
tab1_id = final["tabs"][0]["tab_id"]
deadline = time.monotonic() + 10
while time.monotonic() < deadline:
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
            sock.connect(socket_path)
            sock.sendall(f"activate-tab {tab1_id}\n".encode())
        raise SystemExit(0)
    except (FileNotFoundError, ConnectionRefusedError):
        time.sleep(0.1)
raise SystemExit(f"timed out connecting to GUI test socket: {socket_path}")
PY

  IOS_ARGS=(--device-id "$IOS_DEVICE_ID" --output-dir "$IOS_DIR" --scenario runtime-view-e2e --trace-actions focus-pane,input --trace-input-command "cat <<'EOF'
$(python3 - <<PY
from pathlib import Path
text = Path('$WORKLOAD_DIR/pane-2.txt').read_text(encoding='utf-8')
print(text[-4096:].replace('\\r', ''))
PY
)
EOF")
  IOS_ARGS+=(--use-existing-server --host "$HOST" --port "$REMOTE_PORT" --socket "$SOCKET_PATH")
  IOS_ARGS+=(--target-viewed-tab-index 1 --time-limit "$IOS_TIME_LIMIT")
  if [[ -n "$TEAM_ID" ]]; then
    IOS_ARGS+=(--team-id "$TEAM_ID")
  fi
  if [[ -n "$VT_LIB_DIR" ]]; then
    IOS_ARGS+=(--vt-lib-dir "$VT_LIB_DIR")
  fi
  bash scripts/verify-ios-signposts.sh "${IOS_ARGS[@]}" >"$IOS_DIR/verify-ios-signposts.log" 2>&1 &
  IOS_VERIFY_PID=$!

  python3 - "$SOCKET_PATH" "$DESKTOP_DIR/final.json" "$DESKTOP_DIR/two-client-remote-clients.json" "$DESKTOP_DIR/metrics.json" "$HOST" "$REMOTE_PORT" "$IOS_VERIFY_PID" "$IOS_DIR/verify-ios-signposts.log" <<'PY'
import json
import socket
import subprocess
import sys
import time
from pathlib import Path

socket_path = sys.argv[1]
final_path = Path(sys.argv[2])
out_path = Path(sys.argv[3])
metrics_path = Path(sys.argv[4])
host = sys.argv[5]
port = int(sys.argv[6])
ios_verify_pid = int(sys.argv[7])
ios_verify_log = Path(sys.argv[8])
final = json.loads(final_path.read_text(encoding="utf-8"))["state"]
tab1_id = final["tabs"][0]["tab_id"]
tab2_id = final["tabs"][1]["tab_id"]


def load_remote_clients() -> dict:
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
        sock.connect(socket_path)
        sock.sendall(b'{"cmd":"get-remote-clients"}\n')
        response = b""
        while not response.endswith(b"\n"):
            chunk = sock.recv(65536)
            if not chunk:
                break
            response += chunk
    if not response:
        raise RuntimeError("empty get-remote-clients response")
    payload = json.loads(response.decode("utf-8"))
    snapshot = payload.get("snapshot")
    if not isinstance(snapshot, dict):
        raise RuntimeError(f"unexpected get-remote-clients response: {payload!r}")
    return snapshot


def verifier_still_running() -> bool:
    proc = subprocess.run(
        ["ps", "-p", str(ios_verify_pid), "-o", "stat="],
        check=False,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        return False
    return "Z" not in proc.stdout


deadline = time.monotonic() + 240
last = None
while time.monotonic() < deadline:
    if not verifier_still_running():
        raise SystemExit(f"iOS signpost verifier exited before two-client diagnostics converged; see {ios_verify_log}")
    try:
        snapshot = load_remote_clients()
    except Exception as exc:
        last = {"error": str(exc)}
        time.sleep(0.5)
        continue
    last = snapshot
    clients = [client for client in snapshot.get("clients", []) if client.get("subscribed_to_runtime")]
    mac = next(
        (
            client
            for client in clients
            if client.get("is_local")
            and client.get("viewed_tab_id") == tab1_id
            and client.get("visible_pane_count") == 1
        ),
        None,
    )
    ipad = next(
        (
            client
            for client in clients
            if not client.get("is_local")
            and client.get("viewed_tab_id") == tab2_id
            and client.get("visible_pane_count") == 3
        ),
        None,
    )
    if mac and ipad:
        out_path.write_text(json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
        metrics["two_client"] = {
            "host": host,
            "port": port,
            "macos_client": mac,
            "ipad_client": ipad,
            "remote_clients_snapshot": str(out_path),
            "expected": {
                "tab1_id": tab1_id,
                "tab2_id": tab2_id,
                "macos_visible_pane_count": 1,
                "ipad_visible_pane_count": 3,
            },
        }
        metrics_path.write_text(json.dumps(metrics, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"two-client runtime-view diagnostics passed: {out_path}")
        raise SystemExit(0)
    time.sleep(0.5)

debug_path = out_path.with_suffix(".last.json")
debug_path.write_text(json.dumps(last, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
raise SystemExit(f"timed out waiting for macOS tab {tab1_id} and iPad tab {tab2_id} clients; last snapshot: {debug_path}")
PY

  set +e
  wait "$IOS_VERIFY_PID"
  IOS_STATUS=$?
  IOS_VERIFY_PID=""
  set -e
  if [[ "$IOS_STATUS" != "0" ]]; then
    cat "$IOS_DIR/verify-ios-signposts.log" >&2
    exit "$IOS_STATUS"
  fi

  python3 - "$DESKTOP_DIR/metrics.json" "$DESKTOP_DIR/summary.md" "$IOS_DIR" "$OUTPUT_DIR/comparison.md" <<'PY'
import json
import re
import sys
from pathlib import Path

metrics_path = Path(sys.argv[1])
summary_path = Path(sys.argv[2])
ios_dir = Path(sys.argv[3])
comparison_path = Path(sys.argv[4])
metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
metrics.setdefault("artifacts", {})["ios_signposts_dir"] = str(ios_dir)


def percentile(values, p):
    if not values:
        return None
    sorted_values = sorted(values)
    idx = int(round((len(sorted_values) - 1) * p))
    return round(sorted_values[idx], 3)


def summarize_values(values):
    return {
        "count": len(values),
        "min": round(min(values), 3) if values else None,
        "p50": percentile(values, 0.50),
        "p90": percentile(values, 0.90),
        "p99": percentile(values, 0.99),
        "max": round(max(values), 3) if values else None,
        "avg": round(sum(values) / len(values), 3) if values else None,
    }


def signpost_summary(path):
    text = path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""
    attrs = re.findall(r'fmt="([^"]*remote\.[^"]*)"', text)
    events = [
        "remote.connect",
        "remote.pane_update",
        "remote.render_apply",
        "remote.focus_pane",
        "remote.input",
        "remote.set_viewed_tab",
        "remote.heartbeat_rtt",
    ]
    counts = {event: sum(1 for attr in attrs if event in attr) for event in events}
    elapsed_by_event = {}
    for event in events:
        values = []
        for attr in attrs:
            if event not in attr:
                continue
            match = re.search(r"elapsed_ms=([0-9]+(?:\.[0-9]+)?)", attr)
            if match:
                values.append(float(match.group(1)))
        elapsed_by_event[event] = summarize_values(values)
    return {
        "path": str(path),
        "counts": counts,
        "elapsed_ms": elapsed_by_event,
    }


ios_signposts = {
    "os_log": signpost_summary(ios_dir / "os-log.xml"),
    "os_signpost": signpost_summary(ios_dir / "os-signpost.xml"),
    "os_signpost_interval": signpost_summary(ios_dir / "os-signpost-interval.xml"),
}
metrics["ios_signposts"] = ios_signposts
metrics["artifacts"]["comparison"] = str(comparison_path)
metrics_path.write_text(json.dumps(metrics, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
two = metrics["two_client"]
with summary_path.open("a", encoding="utf-8") as handle:
    handle.write("\n## Two-client runtime-view baseline\n\n")
    handle.write(f"- host: `{two['host']}` port: `{two['port']}`\n")
    handle.write(f"- macOS client `{two['macos_client']['client_id']}` viewed tab `{two['macos_client']['viewed_tab_id']}` with `{two['macos_client']['visible_pane_count']}` visible pane\n")
    handle.write(f"- iPad client `{two['ipad_client']['client_id']}` viewed tab `{two['ipad_client']['viewed_tab_id']}` with `{two['ipad_client']['visible_pane_count']}` visible panes\n")
    handle.write(f"- iOS signpost artifacts: `{ios_dir}`\n")

actions = metrics["latency"]["actions"]
actions_by_name = {}
for action in actions:
    actions_by_name.setdefault(action["name"], []).append(float(action["elapsed_ms"]))
desktop_action_rows = [
    (name, summarize_values(values))
    for name, values in sorted(actions_by_name.items())
]
streams = metrics["throughput"]["streams"]
top_profile = metrics.get("profiler", {}).get("entries", [])[:8]
render_apply = ios_signposts["os_log"]["elapsed_ms"]["remote.render_apply"]
ios_input = ios_signposts["os_log"]["elapsed_ms"]["remote.input"]
ios_base_rtt = ios_signposts["os_log"]["elapsed_ms"]["remote.heartbeat_rtt"]
desktop_base_rtt = metrics["latency"].get("base_noop_roundtrip", [])
comparison = [
    "# Local Desktop vs iOS Remote UI Stream Benchmark",
    "",
    "## Scenario",
    "",
    f"- seed: `{metrics['seed']}`",
    f"- bytes per pane target: `{metrics['bytes_per_pane_target']}`",
    f"- total streamed bytes: `{metrics['throughput']['total_bytes']}`",
    f"- aggregate desktop control-stream throughput: `{metrics['throughput']['aggregate_bytes_per_sec']}` bytes/sec",
    f"- macOS local client: tab `{two['macos_client']['viewed_tab_id']}`, visible panes `{two['macos_client']['visible_pane_count']}`",
    f"- iPad remote client: tab `{two['ipad_client']['viewed_tab_id']}`, visible panes `{two['ipad_client']['visible_pane_count']}`",
    f"- desktop base no-op RTT: `{desktop_base_rtt[-1]['elapsed_ms']['avg'] if desktop_base_rtt else None}` ms avg over the control socket",
    f"- iOS base heartbeat RTT: `{ios_base_rtt['avg']}` ms avg, p50 `{ios_base_rtt['p50']}` ms, max `{ios_base_rtt['max']}` ms",
    "",
    "## Desktop local stream",
    "",
    "| pane stream | bytes | chunks | elapsed ms | bytes/sec |",
    "| --- | ---: | ---: | ---: | ---: |",
]
for stream in streams:
    comparison.append(f"| {stream['pane_index']} | {stream['bytes']} | {stream['chunks']} | {stream['elapsed_ms']} | {stream['bytes_per_sec']} |")
comparison.extend([
    "",
    "| action | count | avg ms | p50 ms | p90 ms | p99 ms | max ms |",
    "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
])
for name, stats in desktop_action_rows:
    comparison.append(f"| {name} | {stats['count']} | {stats['avg']} | {stats['p50']} | {stats['p90']} | {stats['p99']} | {stats['max']} |")
comparison.extend([
    "",
    "## iOS remote stream",
    "",
    "| source | event | count | avg ms | p50 ms | p90 ms | p99 ms | max ms |",
    "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
])
for source, source_summary in ios_signposts.items():
    for event, stats in source_summary["elapsed_ms"].items():
        count = source_summary["counts"].get(event, 0)
        comparison.append(f"| {source} | {event} | {count} | {stats['avg']} | {stats['p50']} | {stats['p90']} | {stats['p99']} | {stats['max']} |")
comparison.extend([
    "",
    "## Built-in --profiling hot paths",
    "",
    "| path | kind | count | total ms | avg ms | max ms |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
])
for row in top_profile:
    comparison.append(f"| {row.get('path')} | {row.get('kind')} | {row.get('count')} | {row.get('total_ms')} | {row.get('avg_ms')} | {row.get('max_ms')} |")
comparison.extend([
    "",
    "## Initial comparison",
    "",
    f"- Desktop local stream uses a Unix socket and avoids network/auth/device scheduling overhead; its best comparable action samples are in the desktop action table above.",
    f"- Desktop no-op control ping is the local base RTT proxy: avg `{desktop_base_rtt[-1]['elapsed_ms']['avg'] if desktop_base_rtt else None}` ms after the stream.",
    f"- iOS heartbeat ack is the remote base RTT proxy: avg `{ios_base_rtt['avg']}` ms, max `{ios_base_rtt['max']}` ms.",
    f"- iOS remote stream uses the real device path; OSLog render/apply summary from `os-log.xml` is count `{render_apply['count']}`, avg `{render_apply['avg']}` ms, max `{render_apply['max']}` ms.",
    f"- iOS input-to-render summary from `os-log.xml` is count `{ios_input['count']}`, avg `{ios_input['avg']}` ms, max `{ios_input['max']}` ms.",
    "- Maintainability risk remains higher on iOS because Swift mirrors the Rust wire codec and message constants.",
])
comparison_path.write_text("\n".join(comparison) + "\n", encoding="utf-8")
print(f"local-vs-ios comparison written: {comparison_path}")
PY

  cleanup
  GUI_PID=""
  SERVER_PID=""
elif [[ "$DESKTOP_ONLY" != "1" && -n "$IOS_DEVICE_ID" ]]; then
  mkdir -p "$IOS_DIR"
  IOS_ARGS=(--device-id "$IOS_DEVICE_ID" --output-dir "$IOS_DIR" --scenario runtime-view-e2e --trace-actions runtime-view-e2e,input --trace-input-command "cat <<'EOF'
$(python3 - <<PY
from pathlib import Path
text = Path('$WORKLOAD_DIR/pane-2.txt').read_text(encoding='utf-8')
print(text[-4096:].replace('\\r', ''))
PY
)
EOF")
  if [[ -n "$TEAM_ID" ]]; then
    IOS_ARGS+=(--team-id "$TEAM_ID")
  fi
  if [[ -n "$VT_LIB_DIR" ]]; then
    IOS_ARGS+=(--vt-lib-dir "$VT_LIB_DIR")
  fi
  bash scripts/verify-ios-signposts.sh "${IOS_ARGS[@]}"
fi

cat <<EOF
runtime-view-e2e baseline artifacts:
  output: $OUTPUT_DIR
  metrics: $DESKTOP_DIR/metrics.json
  summary: $DESKTOP_DIR/summary.md
  qos: $DESKTOP_DIR/qos-baseline.md
EOF
if [[ -f "$OUTPUT_DIR/comparison.md" ]]; then
  echo "  comparison: $OUTPUT_DIR/comparison.md"
fi
